---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-webhook-cert
  namespace: envoy-gateway
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/component: webhook
spec:
  secretName: envoy-gateway-webhook-cert
  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days
  dnsNames:
    - envoy-gateway-webhook.envoy-gateway.svc
    - envoy-gateway-webhook.envoy-gateway.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: platform-issuer
