# platform/cert-manager/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform
  wait: true
