apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
  # ---------------------------------------------------------------------------
  # Flux components
  # ---------------------------------------------------------------------------
  - path: components/flux/upstream
    contents:
      - path: manifests
        extract: true
        githubRelease:
          slug: fluxcd/flux2
          tag: v2.7.3
          disableAutoChecksumValidation: true
          assetNames:
            - manifests.tar.gz
          unpackArchive:
            path: manifests.tar.gz

  # ---------------------------------------------------------------------------
  # Cert-Manager Helm chart
  # ---------------------------------------------------------------------------
  - path: components/cert-manager/upstream
    contents:
      - path: manifests
        extract: true
        githubRelease:
          slug: cert-manager/cert-manager
          tag: v1.19.1
          disableAutoChecksumValidation: true
          assetNames:
            - cert-manager.yaml

#
#  - path: components/cert-manager/upstream
#    contents:
#        - path: chart
#          helmChart:
#            name: cert-manager
#            version: "v1.19.1"
#            repository:
#              url: oci://quay.io/jetstack/charts
