apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
  # ---------------------------------------------------------------------------
  # Flux components
  # ---------------------------------------------------------------------------
  - path: components/flux/upstream
    contents:
      - path: manifests
        extract: true
        githubRelease:
          slug: fluxcd/flux2
          tag: v2.7.3
          disableAutoChecksumValidation: true
          assetNames:
            - manifests.tar.gz
          unpackArchive:
            path: manifests.tar.gz

  # ---------------------------------------------------------------------------
  # Cert-Manager Helm chart
  # ---------------------------------------------------------------------------
  - path: components/cert-manager/upstream
    contents:
      - path: manifests
        extract: true
        githubRelease:
          slug: cert-manager/cert-manager
          tag: v1.19.1
          disableAutoChecksumValidation: true
          assetNames:
            - cert-manager.yaml

  # ---------------------------------------------------------------------------
  # External Secrets Operator Helm chart
  # ---------------------------------------------------------------------------
  - path: components/external-secrets/upstream
    contents:
        - path: chart
          helmChart:
            name: external-secrets
            version: "v1.0.0"
            repository:
              url: https://charts.external-secrets.io

  # ---------------------------------------------------------------------------
  # Envoy Gateway
  # ---------------------------------------------------------------------------
  # ---------------------------------------------------------------------------
  # Envoy Gateway
  # ---------------------------------------------------------------------------
#  - path: components/envoy-gateway/upstream
#    contents:
#      - path: chart
#        helmChart:
#          name: ""                          # 👈 required but intentionally empty
#          version: "v1.5.4"
#          repository:
#            url: oci://docker.io/envoyproxy/gateway-helm

  - path: components/envoy-gateway/upstream/charts
    contents:
      - path: release
        image:
          url: docker.io/envoyproxy/gateway-helm:v1.5.4
      - path: crds
        image:
          url: docker.io/envoyproxy/gateway-crds-helm:v1.5.4
